services:
  - type: web
    name: text-translation-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"

---

Need help (e.g., FastAPI endpoints, WebSocket integration, MongoDB setup) or deployment guidance!
